# Generated by Django 5.2.9 on 2025-12-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaApuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.URLField(blank=True, help_text='URL del logo', null=True)),
                ('url', models.URLField(help_text='Sitio web de la casa de apuestas')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Casa de Apuestas',
                'verbose_name_plural': 'Casas de Apuestas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de ícono (ej: fa-futbol)', max_length=50)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 1X2, Over/Under, Handicap', max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cuota',
                'verbose_name_plural': 'Tipos de Cuotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=150)),
                ('equipo_visitante', models.CharField(max_length=150)),
                ('fecha_evento', models.DateTimeField()),
                ('liga', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='comparador.deporte')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(help_text='Ej: 1, X, 2, Over 2.5, Under 2.5, etc.', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('casa_apuestas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='comparador.casaapuestas')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='comparador.evento')),
                ('tipo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='comparador.tipocuota')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-valor'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_evento', 'finalizado'], name='comparador__fecha_e_8bd404_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['evento', 'tipo_cuota', 'opcion'], name='comparador__evento__cb5a26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('evento', 'casa_apuestas', 'tipo_cuota', 'opcion')},
        ),
    ]
